name: Build posts from Markdown

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Generate static pages
        env:
          SITE_URL: https://lydia-cmyk.github.io
        run: |
          npm run build:posts
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes"; exit 0
          fi
          git commit -m "build: posts.json + static pages"
          git push
